/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "000196458.h"
#include <stdio.h>


void
programa_punto_1(char *host, char *file)
{
	CLIENT *clnt;
	int  *result_1;
	vectores  p_punto_1_arg;
	double  *result_2;
	vectores  rango_medio_1_arg;
	
	FILE *datos = fopen(file,"r");
	
	if(datos=NULL){
	
	perror("error en el archivo");
	return 1;
	}
	int numeros[20];
	int numero;
	int i=0;
	while(feof(datos)==0){
	
	fscanf(datos, "%d ", &numero);
	numeros[i]= numero;	
	i++;
	}
		
	for(int j=0;j<=(i/2);j++){
		p_punto_1_arg.vector1[j]=numeros[j];
	}
	int a=0;
	for(int k=(i/2);k<=i;k++){
		p_punto_1_arg.vector2[a]=numeros[k];
		a++;
	}
	fclose(datos),
#ifndef	DEBUG
	clnt = clnt_create (host, PROGRAMA_PUNTO, VERSION_PUNTO, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = p_punto_1(&p_punto_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = rango_medio_1(&rango_medio_1_arg, clnt);
	if (result_2 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
	printf("El producto punto es: %d\n",*result_1);

}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	programa_punto_1 (host,argv[2]);
exit (0);
}
